spring:
  application:
    name: system-api-gateway-service
  cloud:
    gateway:
      routes:
        - id: springboot-helloworld-browser-json-ports-text
          uri: http://localhost:9090/ 
          predicates:
            - Path=/**         
        - id: springboot-helloworld-browser-json-ports-display
          uri: http://localhost:8080/
          predicates:
            - Path=/**           

server:
  port: ${port:8090}